{{ $context := merge (dict "app" $.Values.mailServer) . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neves.name.deploy" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{ include "neves.commonLabels" $context | nindent 4 }}
spec:
  replicas: {{ $context.app.replicas }}
  selector:
    matchLabels:
      app: {{ include "neves.name.app" $context }}
  template:
    metadata:
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
    spec:
      containers:
        - name: {{ include "neves.name.container" $context }}
          image: {{ include "neves.url.image" $context }}
          ports:
            - containerPort: {{ $context.app.port.container }}
          envFrom:
            - secretRef:
                name: {{ include "neves.name.secret" $context }}
            - configMapRef:
                name: {{ include "neves.name.configmap" $context }}
