{{ $context := merge (dict "app" $.Values.mediamtxServer) . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neves.name.deploy" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{ include "neves.commonLabels" $context | nindent 4 }}
spec:
  replicas: {{ $context.app.replicas }}
  selector:
    matchLabels:
      app: {{ include "neves.name.app" $context }}
  template:
    metadata:
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
    spec:
      containers:
      - name: {{ include "neves.name.container" $context }}
        image: {{ include "neves.url.image" $context }}
        resources:
          requests:
            memory: {{ $context.app.resources.requests.memory }}
            cpu: {{ $context.app.resources.requests.cpu }}
          limits:
            memory: {{ $context.app.resources.limits.memory }}
            cpu: {{ $context.app.resources.limits.cpu }}
        ports:
{{- range $port := $context.app.port }}
        - containerPort: {{ $port.container }}
          protocol: {{ $port.protocol }}
{{- end }}
        volumeMounts:
          - name: config-volume
            mountPath: /mediamtx.yml
            subPath: mediamtx.yml
          - name: {{ include "neves.name.pv" $.Values.efs.name }}
            mountPath: {{ $.Values.efs.mountPath }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "neves.name.configmap" $context }}
        - name: {{ include "neves.name.pv" $.Values.efs.name }}
          persistentVolumeClaim:
            claimName: {{ include "neves.name.pvc" $.Values.efs.name }}