helm:
  parameters:
  - name: image.name
    value: public.ecr.aws/k8s0f8l3/neves/play_server
    forcestring: true
  - name: |
      {{ .Values.offlineServer.image.tag }}
    value: dev
    forcestring: true
  - name: |
      {{ .Values.dbUploadServer.image.tag }}
    value: dev
    forcestring: true
  - name: |
      {{ .Values.statusServer.image.tag }}
    value: 4abe68becdeb989068a5e0c40a009793330d2a0a
    forcestring: true
  - name: |
      {{ .Values.userServer.image.tag }}
    value: 4e05b1cdb37a4d3a9b13c9a0506df596164dde57
    forcestring: true
  - name: |
      {{ .Values.mailServer.image.tag }}
    value: 24e8e92f6b30aa8cbd13b35a7036b9ba737a31cd
    forcestring: true
  - name: |
      {{ .Values.playServer.image.tag }}
    value: 682fed9da3b2c92a0b682666f0bc68ff5dd50a19
    forcestring: true
