helm:
  parameters:
  - name: image.name
    value: public.ecr.aws/k8s0f8l3/neves/play_server
    forcestring: true
  - name: |
      {{ .Values.offlineServer.image.tag }}
    value: dev
    forcestring: true
  - name: |
      {{ .Values.dbUploadServer.image.tag }}
    value: dev
    forcestring: true
  - name: |
      {{ .Values.statusServer.image.tag }}
    value: latest
    forcestring: true
  - name: |
      {{ .Values.userServer.image.tag }}
    value: latest
    forcestring: true
  - name: |
      {{ .Values.mailServer.image.tag }}
    value: e38acdf4f92e386a05eace0dd02fe6ec75af029b
    forcestring: true
  - name: |
      {{ .Values.playServer.image.tag }}
    value: latest
    forcestring: true
  - name: image.tag
    value: 682fed9da3b2c92a0b682666f0bc68ff5dd50a19
    forcestring: true
