helm:
  parameters:
  - name: offlineServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: dbUploadServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: statusServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: userServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: mailServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: playServer.image.tag
    value: DUMMY_TAG_FOR_BUGFIX
    forcestring: false
  - name: image.name
    value: public.ecr.aws/k8s0f8l3/neves/play_server
    forcestring: true
  - name: image.tag
    value: 682fed9da3b2c92a0b682666f0bc68ff5dd50a19
    forcestring: true
