apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: slack-monitoring-contact-point
spec:
  instanceSelector:
    matchLabels:
      grafana: neves
  name: "Slack (Monitoring failed file)"
  slack:
    - uid: "df372ayf3ad4xe"
      disableResolveMessage: false
      url:
        secret:
          name: grafana-slack-webhook-secret
          key: slack_url

