{{ $context := merge (dict "app" $.Values.combinedVideoProcessor) . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "neves.name.svc" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-name: combined-streaming-lb
spec:
  selector:
    app: {{ include "neves.name.app" $context }} 
  type: LoadBalancer
  ports:
  {{- range $name, $port := $context.app.port }}
    - name: {{ $name }}
      protocol: {{ $port.protocol }}
      port: {{ $port.service }}
      targetPort: {{ $name }} 
  {{- end }}
