{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCYvQmZ6GebM+hAeAaAykf+vFA2jdVmilD8/XEYNmO+ngGDfK+pbXAYn8fAJqYwI9lKCwxlVHh+rJ7kPdTKzDUFwWchKtG78g39bTSf0/NyEn/0dMpSatTiP0+CfPDd2h8Y+B2KH3AMaXNPnKfPRrxEEQaErhISaVECGgi6mOujXNgDN8bm2sSUiexdBhE2apzqUN15UJjYn07WKsa6jKclKfjBVMeuYX5dlXRMxRhZev+ME43lw+JPWYzLyVvrPTq74AsL87uHRYLfeu6s3+sKDTWdhXZkEjSoR/4hwoeQIxqU531kzp/mHSfHvlM+oTGNyHCx6GcAwzVWRaaUhzV3F27iWDkOPc+NoWJ+4kaakz4TPlf9Nhi6sVuRaFMFKnZ70BJtlzko1ZRNeOi+YB2MeXsNKbCxXvHV3YABosKDhNaHMXVGHmq8SHb1HdPVr/QjXvkm+zJKVgl8rH125l5kNJRrrL3k6P9v1n+6YZSfLC0Aa4mKZVmGKcnzu8JAOf6zfYhc1sAjlUEkO8B7JEgDSWodGwC9Pp9v6c5AXOd/MolB9elSWIzv1bx3GFCIpOZ8sHz0TaV4akRxS/50AmZdBZu5KrABTGqf9fmWDTF4itle/2S0hglDqIF1RUh3rXrj8kx3ALJBzErod6iHjt5IHH0C4E7HyhLyYh9nn8ryPhg+sZ0Qr36ZAsJgZ83pGKmRreygHvhaWx5PUU47YuPUtcgBTA==
    AWS_SECRET_ACCESS_KEY: AgCqy7zvuCbNKApuvIgTIlJm4GhO4DT+GumAxtSf4/7byDHxKCx5kGsF/qZtNyRDlo0ABxoXFOdpXr7l0J+ipsjx0t2rhcJNmYGIBXLJ4hakLrOE/kp89ivplYbW0XOPZ9sKHKHs/UbDmYytGW/tcsDYzyEl9DxqZIyD9z9D21ciajhjhyqG6pUBr7o0jbbZK9FYleCZWF0dGPLJeVsFsJ8/AUXchLc3bqfQ2xtJExQE0HJRkt9GopH4JGZ3ago6Nz3duKBzt9s/BaX0bqSogIHikrNKMaWHyklZ6IAPtAtzPBFJ9iHqMo5hzvYwQJWPOKf50dFYHNt5iZvKSj1Fk8ZoN40Y3hMj5seFx6Zy6nBm48LfpKIMzCfJK89OFPTw1gMuDqRzX14YMfbFIuqN3R1WtgsdTWv7yTZBn9zh2QmFuCVJXicGG71nuF+HSE+KoRd4DwHMYpc2dzNkSqmrBGfikPkQ+vESaSsDJcsYQ+1hUTrvXpxmut4xh0MVWbNz+du24TzyVjiVkhExMK/D2fqgxNh+Z7AYopPqoegkMbRaeJQUxti+dJj3BFJy6FUhoK+KFFT28kYMqOCV3nUAPVJyWzUFjPdG03R8wcVIAfvV9bXmf9NAZQnz6nsZb1fMf7Qwb1QsiGZvgWLjxK7OO2vWIxAFlsJ5YCX2eM64Ssf2G6Sjk+tGchFXjIosRW4j0e1054zF+mvF9F7+bZBeFPTSqCZ95dY8eVwlCz2EO2jxnKejl11y+SQC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}