{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBWZY81xON41u6gP0mAoyVwJ99NdkUqjsogx49afbJrB/eNsJ5l99RBdbcI05MYTJDpZ4PDNxxC54w/UxwHJmYVFIRKn/+yaT5Xy8THxuXoFAops2QZYmPUQmlhUKHKfM4F2jgrMU/yOVod23T7qmFKvPoHxl+T3oLH6AXH9IltmCU3P7bR1+3bj0cCx39muMf3NuZvlW726T9oyXtCn6eRLRU5Gc2EDxizzR/ALPMz3hCPHhRCpxCR3mxaoQh4yksAoqQhgZOCzfXIBHWowg0W+VcIZX7R7j0vVSEe5+35DSp836Zoz8fUHfsg3EHvV/xbDp3QcaRMNgU6dLtyxQZnz6t+wrIAbcx4Fmm3NIw3G3NMPC7CC9epJRz9Bxm2qXB8MeJI4eoIWeoV7JgJgq6UNQUKSBf3D5EGiyRXJNIr471fwXjwvKrAewT7vDR9XC4QmR6sC8FkNAfLOZd9tAc3Wna/7CPhGIQyw82TIBdIOEduhFnHkuyAK3Qf1BSPkMOINS2W07nEcjdaE5WdaHstSf8yvfXFNJnP5Jv7E4Y00+1on7AMvqxHUpYJJhDu7uso1hoU4Pq4AyZvFl5VypeXP2J0rJOMaE5tXY4PM8LnPZyjvndtLzz/q3/KUhmx7ov3OTos3oOaWnNsowBp3rFs9ElA2EB3vubTc31oi0k61/oYp6kmDznLXgSgn9i9T6/JoPLXjyKp7xo27nmbCSDQqG/QYA==
    AWS_SECRET_ACCESS_KEY: AgBHLeLkkulG+fQV9pM07yIUd07DLvUtewcorJsIxW9mrcgZNkR8c6cWD3NQHx1S69N3QpUDsx7FdwkLvD9BYpSFBO/reorRaQP56kBkJiYT2c+EuT9eBLrFLMnkVFT9a0xLc14+njRHIsevffAarIcw47jdQNcC2i/YhCmoGnNgbrqhjQcNf4HI04kfJqkJnGsCAo7lwWbeACcOTFp+kfHD7Wj5ixiQqG4v24h+aEnJNt3UBc2oFoY+qA533GPKYBZKHTUr9ZmCMIl3Ub9DsrsxNpR3u3UM/MbLOO2I2jEWnD1c3QWrMNMqMNBA3jAcJmjSIVftEYK0/GTFqYcqcnSbxwUqcc0KwCPmHaZAurlVTz5Ad6uPUo9hKLp3CK/+yGvmE70DCvsp4wLLxf6Ez6NKt5nPI+RS3tkmNcabP9Fr6uY6AjbDjvigMjD+j8dQDI8IynN2wW8Yia1f5Z3bfzngvFp0TF+W2U6S1W9wgoqzA6hmogXtMWxWxDR4xdtFsm6F8ddFwrhcDzSvNrDBDYxteUPGKChgD0PUrVEtlLdiO1hoMHQHolEjxuDExu//OsM9scGzTbOBd9F/YWXbxp1058am907B5KVA4V+GuG8Kn1/cpYuIgP6LvfqCbo5LPSUI960fYvH5nivXVPImFfdnymyGmqYclIYxIqluNpIRY8pOG2+dBvFPmzufzZ60BEff/OPg7IQLIh6cWzb8MsL3fs4mQ1xkhCX/l9iHi6UD3ePbozpWUTON
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}