{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBbai3+yBK9OKuu1pBOQM0orcENr3Yad1j0OQb2eXsJUvcFWd4r09BFU8dgP4W6eCJquXbPKgjTbGMhJemZirZLUZF2wAhCekr+VEOoyNRu01WgdR7QSEan1ZF+VfEqKCKoPGHCki+VYlW1c+d6eI969MIPkolx6eKFM/DjdxMpAu7nNHOATSjvlU/uTeHahxH9uU6gdUkO+dpZ0uWmfetZCjB+qIlohFuuoEHInWgWYse6hjMuPkMJwp8nYrd2zd10Qrn4iBj3/iy6xRHPZ+bsKYNGeirPjGLrT0smAU5Km/QARlMKRs0aOdHrNlq+9snpehcvIg//GP6i87OgFwm4Zc/QOFYoRoHhxSJ5u4b27EV+HEzLDZtGfYFSgnbtLpmvvyqDTEceaccWJ6BR9Aqj2VRa9jI/ZaQZSWNvBE7JQvRri4g1TC34p4tsQO6X6Z2YxfUezYOhHtYYXGkbAQMKCCh601eC25Zs7NRREQZrXjxsBo7L4uDd7CfSHmm/+/+OOccbHCYLifIHHGkuc06oWSqYISRzLN8zIOvIdXv9o+N3Tn6yh3XIAHeVPlHXzjemKs3d4AFfD5qhTWRhWTxFDzYktepnNbtQtg2jdybe/QWxCRuI/7OUHLi08eqOdTo7pBiWAVAn0TWMF7NFxzbVvNboykgmDXp6CpiJBoDjNQc/RA6nhatw1Ub+2uhoA9Weu59ewa+ydCInerxCyRheZ+wE+g==
    AWS_SECRET_ACCESS_KEY: AgCbMA37tMUa1bQt+97sXTHqO5mDgAu0UXJcQVNkUsX1KOb9+quOHFyyMtilHPzoBq+qAz+Qdx076qs1nIUrvBNJE8P/3GqSs5Zmpxx7Nmtu2sD+JflvBORBnA/0jyxvaKY4IpWCqx5+e+uzaDzlAbJnwRXuU75Q177Vta0Bug85jmoui/xn9rK2o4flaciZSPmSPep7rysAND88aCGUS9e4p3godxndsrO3iV1nZD06J/epwLph4+r6xUJXpT6Vu1y7VyDsw6WUf/YyklkGtGV3ZBcTQTChTTyCRvCURXSp7TL5sgZOd3Z9ZiI7AzWiIEUukW/HhwS8mNjiET7cbkCKNEimA3emt2OL5kjW8SN44heAHV4O5rHWqDqVV+2vLUpRteHEpg5/c3NJTg0ME9cEWHiwzZ6chIhcgVVAIUNRfdxqckgLAgjNDgJTpRAWXGTl61Vjxf104hW//YRa0J/x9ZmJyZ/f/3DKZqAUdL6SVGtYoN3h1XVolZBaDqrnvfs3QpY5zkyCeTv/HKLh8YdlXQmrPNmUjkOBaYPl3JpnRT2e5iOZNGbb6sbVWkIaUJwEbTBgBAfvDUX91zOZZMiFRD5H4835IUx8wYL2eBtFZuk19MMmjOEBBjqIEHVkbSyAzgHqfA7H1ggu9cb2jTAPe7CdNcebJ7/FSJuXI/BeD3/XcqRRtlYpjXeQGsPFKTmjYgXwI9wf9O5aag463UNNx83Vmz7n666XGKtpfVZceNa9Em+TT0L+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}