{{ $context := merge (dict "app" $.Values.dbUploadServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgApbOfcxFEFenVEoc6F1l1F7FQd8TVDvwdvsZyckCcqwwGGekhwhE7x1PJPcv+lWnMD+Di67NMfwrdFHHJs01xfG1LJHU60Yc6rhiQ87piiRzaQDXB3TZzQ1Qe47Zf/U46kykiJsNecayraXjyFr+AeUQk+53YyVFSbt8sjonotSoQZg+TOygvHaLIFr4dA+830rOaa2Cu3plMl7x2OslDent1P5sY7yzionew8F+jojwQuqXBGSk1n+Hg1KZH2OvFdokzg5BIKYFUkZHbJ4CweW5jMACJhMcoG3RsuLIVsOEqSC6GeVebiH41vZoD4I3fuoebvkA9QjMvfVRK5lchbWyHe1lAAiPoeXpjZjcbQ5vjy/MEjhzFmYjv46VWjmVO6bVds6t2FyzD/H5Q3I0sSDNhKUDrdf0nuKiSoTlY9NB06LTYrtgwe5qzz7I5DlfU7uWDlsyP6jZZkabOD8qOlIIV54LNF2Gr+3JF/wP1v74xaq9wJOh3EtnmgVkJ/5w7OmBMcbKC485cjTJ7QBpnuh3AVt4kW9G5QWVsgb+a0G7pNatVbkjAEQR/KnTPI8KGoqa0956Ow5AtpR3Fm/Cp7HUG8oZe3C5eCAEXV9kjuDdpMK3/1LVoEdpc+jM5q+0GtwuddZQ740alarfpo8PLlKUDJ0njr8mQzFG23HPSKRKA5j0Y40Mk7qvI6oKMebfg5MkFksssdrsnMh9lRFphQscx70Q==
    AWS_SECRET_ACCESS_KEY: AgCCy1SDAO3/y47/Pl3BtsUZcUUYSR+qFLTJXw7aSY6iu0nn4ezDENfdzjdXkdH/BBGaLlItn3FAJdaGZzp1g4coC8rb9FiJ4O4Id+w3CRTVDpquNzpE7iKVTKuVHi7tPe8YOwXzRGGzTxHpumbhydDZQzLzV8WCeSirb6LXhQDeqngu5ngOD6KGQuE2eiNeQSR8UP++Y+j1AlY3ju2lSoNu+LyRjU/fA4OIzg/bTIEKctSR5muDGnGfV87NL2H1jcRxFxr11liQwPu+Setn1WK/dOWVeJxfNiHxdDvJb5Cr+E0WBHgKl2A0pqp+OmYfPOJJ/rsW+Cfy4rb4I196igLW7otxxSzpjwliaWzmwvR+7mibMfdtaZA9amTasZcZJolV73Fkn1Yll9lxrqirfZqeyiYlBGS2S6StauAf78SE9bYEiYMh7CZ4mRC95IlFZP9oEEK7ycIJHmZTSF/hmQTUcP0JrV4julr8jH5wFva8T1J5/ntisTBy2WHzmnqgEde7mQEb7Qmatve1lk/GdWjgqjxsBjDPzJBBZ6oRfG6dYd2q10DMjRohaIBlxtNvYWqOc66szJlMun71ZslfiurtKq68R9TvMwyD5EdNXr8GJ9MXW1qBfcqHgZXHNtwQQkjSHqli/GrgwkNzqS91J1mZ5XIamOoF6VWWj7rzVE9MLrM9TSeruOotpkVzF3s2QkyjuxPaTh7y7t7J2ZsbyJGXUNwnytaeu0tJ5l2hqvZS6Bf5M4UzCMXG
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "neves.commonLabels" $context | nindent 4 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}