apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-slack-webhook-secret
  namespace: {{ .Values.monitoring.namespace }}
spec:
  encryptedData:
    slack_url: AgAnfsCn4S1eebo0u98ddC4qx5StKnX+HLjUMayCpefYOduwyuXU7tYcCD7hM0SQZJ90W/cKapfGcp96JLMlqeWfv2oTh6kENwwfSCZ7dx6jYxehWPe6x6sxUZaregTKdPUUoy9MzQ+7wqnTr5PmpwZN61/70RtXFwSXRPQZuxHQqK6mTkCiGkiSFvZLnzR8duLVzmUu6zCOEf0gHZyE7aFFqX71/rLefSiau015NZKJ7uISQBfMRvfsZ3CYzlA8xXpxKfD03LXbY2oYnYoaC0byRJgi0iCyAC2EfuwDYGi5eIROZk40rZcwei9GyCg0TkKA0yadMq3BdscrPeZFvrYhZ+IcyFJsJDWUWnWbnI6Bv5aCOKOfkymbjA0R+kQyannKbGxcpB5FLNLWviYBznIBoPvRX4BTIhMZelBH2B/Pa6UYR+QpfANCRzlT09XTJW77hzucxmLRCQzEny7DTaS4cmpf9uRSVmIzKNXf9lzPWS8PDRVNsY7MVgw0B4bjb8dw0wX8Ux0pRIdKoQ+MQr8lkytZbl6V4QLL65mkSQ5o/YP5Bt6LSmv+UOnJscMNwTN+LJZ4CqyIPTN2rCh5hinzVRxm2NXTAk+pVzmg3ShsS70pj6uKLv01l7CEvwjeeRIZemA+XAzqsfddCo1aaGgOTm/p/B0jgQ5xgxrXZqX61Zrpnzrz68tzobBB2pQJPX9DnrAChiYO8npqjXdhBTxSLjz02BqCIIE9GFxmgEpai6jxF+9FL6SaXDDBHu4v3/g98FQajZ8ZDeIDvDLC/vURWdzwwTXcwzuVphhmgdqs+9U1I8eW4JrPeMpFEvbKtf28YTpJpw1f1DKle4o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-slack-webhook-secret
      namespace: {{ $.Values.teamName }}