{{ $context := merge (dict "app" $.Values.mailServer) . -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    GMAIL_PASSWORD: AgBkYt2ROyzxhZIwHXjLw3dfcuZ6Q1zCzVF3lYD5OAB0nkdEjB+IDS/PuiS6m1rRMWr03sybyvDsMMARNYwV0j00skTq55P90g17T2EPBOezYLYVIKWZBN8Jz7I6+L2/E8cWKd5sGbZQGNv8mRz35zpNlt0RseWvdWeCBBoP1FFXd6WPHgMpZf+U8ID3L6xGLsitqlDVqQ883NkdMMg+sIvmD8Z2aHyJrVWbINVRuA9ILAhEV3Yaj8NF+tup9RIOqLqQ3OjA+bXmU8ojvN1jDrRtdNei6F5rRiIaaWpoG/Th+6OCElxkZVKpbDWIvP0zP/br6ikEEfV3yFhUYHNlHgfUyvFQvKy4BOE01fdmCau3PVwcwYuoqLS93Tu6RWblXH2AzQNO0FOKo2eyeFXKwjqPEDeKcF8yX82ybcSt0RRqKE6KyjHkw7kpmAI63RlR191g9TPI1xamcRufawL8qoUyTNkmagPBPYC47xXHkIJyJfbStdoTPDHoih108+DbIjKofsamiWsCcO89D3C3Lij1ps9VvO+JYWoj/grnluDNDpCIySnOedBVBJ1HwTn/Xbp/AI/bGwHyauNFj/fVtS0KF1hMyscyW+aF4VaBo3+A5hMowBOwu7U65Mu3wWJl28U3bDt0c3X8GmM4gk/7lTdqdXrRZU4orNtYq01SV8AyEJZz8d45SejAr0ICJAcx8Go3+P820VlJDN//Nnl8RMwCA1Tx
    GMAIL_USER: AgARTA2CBRos+Cm6cbufpCRjHMNwS0UuqXAUK+kC329KlPnhz6HJ2xsOgNP6klGi1gysksZLAd+Qz2OzeqGp3VnQpbVIDQp4DWld+gZ2ZNyWiR8lHUGNdWHWlzTSyacE/apdmNVRVdVxBKNwi+R7Z7j5VEa825vqjLapupVjp/eInEFwKrmXkJLRKmRRcWMe6vFtHvOoiAyIQnIyU2LgXtiQsTXwvPuYBwQsjrRmPBPtgawinb2dzD8dw93/RzQ56oMtManCQw575vRBUdBL3IhnOxBHX/XvFG3Jvcaw2h/AubecbG2fPPfya20HaiTMJykfIIOD7AbJQZKzEVZexgV1JkHcxnqcUTQLm3ToRnw6usyQAo5Kp2s5YXD6/xBBfQnIwVcyNbQFkd4SpmUygoQxPYv2+hVUGvv6gEVDMH3UbyefqXOri8Xe6rKxViwcQEdfUl0xVwDN0Agl9kkuJuifZgM7ulARe2idzNcGU2G/gNGM+pyzS5w9Db+ZrW89oLvVhgah6WEzLs2QZi1DBl4y4owSGQNEV4kKpDHs0EJrbfIHL+lKDyYQyORdau1+n8uFusTnHBzeZ77ra7MwMUxEG7oPcUyvgY5ZMTvYhBsJn1oMTz+bpdLHeD773KKUKPCOFrQl3x9+RbMQxCZv6HUW7rtDXLXGhskk4lIoeIJOUFINCFv2vz3Mj5A+2PKhvyzeYGo/Ds7NQeNV+AZ9Q/TvIEalwSye
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}