{{ $context := merge (dict "app" $.Values.mailServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    GMAIL_PASSWORD: AgA/I25aAf1eN6DnmflsLKrzhzoNnHfrMl549O0VGNb049zg+IazLjZxk87Tf152oByphN/xkaVV0HesE/ppWsO3F1ahPZkLbrZNoZDZu9Y1UO422s9GG1JXvid1zokCpARnEiwmnocBL85UGWRfSzOzJBqkepnIrceTNjjrze3DLa9mRZWPRGMKopMa/Obpq0tqDqPxO6ZZX6We14h1Ngxedx8cU27TyAafz/NOfYtsiRylyhHdMyUMA4WX0arkACS6I4X6CHq5/33iEhQtY7dGC1D+1dAAbJrDugmzd82HPNYuZ+TxP08D26fJ1IoqbUlMQIMxmU/N2Nh39usmQfVbyVPkYV24OoTwqvylDpKEczgJn1LN+D/D/RuueKr8/PB1CIYIrI1KyX98zimSYZAJVqQqGVzrQhMoDaxpuI6XG6aQ4HBb2zH1nsx8fETqh02nx/CppQqH1sX5lIi7mFnD6UEkRyB/O5TP1kNjEzLNzHHyRefYqxgpbJo58BRzcK1rMPdU9WpOuhUxSX6GAVjmDHU97wrDQzNDWM/u9USjaytxzR3YTdk7QONDLLszEMjwEVAk8SO9qHPWpdWfCl2xFa4jppbcW3jieVjdUm25UkQNauZ+NjpiECHxGrg2i+4Ro0YVAJmthZXCW1DV0EE/v3BgELktGqqLos8YpwCB+6CHZvErXLm6sS6pjtdA/ualTHN9ZtmOyY4wzz+wx6Prwm5P
    GMAIL_USER: AgAAFBveKi/+1FPZNgorRFxmXEfva9o6KtrqrdrFn2TLDylmIdT1OUvXix40dhMqIWP7J/4OqLA7jeNtlt8vofOqcCb2cLULhUATnXJCbtckCWdplviYQWAl+DSaBv3zGqKeaegtWYyQobDW6MORXmD0TtnkHT7JJTwwbT+yYDRqpnJFVlHUmelXJuAv7RUGC1mqyatTFs9xM8z2XY2xdAkRkRzVl8p7TJjnIwFIt0QVXyJCqQlS+b4/0ydfvlr9d6Uhlrqcu2hg8Td6AEt3ELYdd6hGEwnhdQMpq5qCDlGuAdScuj3Ic6ZCO4N2bpkAwXuB8tXPVOWulZAMPTThdHo6071ES31M80KDUJLqEGK5Cc25ggLG0d4RFq+jag9Qxu2GaePDcyRPvmQfWRCB4ybNSxxSu92hsDkT58nWWOU6Qk3KCgAf201cFOTdHbWhM9eRNc8tYJ9SQOFuZ/tQy5X2SK7sNj0AYwVZPaVC55lWPZxkNmpnUqcqGgUB2YmULE2iABwDf3PjRugwoMqWqVFbeyvKrx1NfuL8urPWXxbU7eeQztuhX9/SyIA3HaT0rLCHvxvkwvfglqKA97ahMzaO0lBHk/nA7stkXpFQsaIPHn9lSNAPoeUNqyTQwtDJgd9aVA8H3mifn9PLXM3uoq7Kq76IJvz65HM3R13fi+5IzUTZtyTTxU4PsYMmE5iEHwPBI3WTfJaekYbXmeLvDrV/wLMIPgL/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}