{{ $context := merge (dict "app" $.Values.mailServer) . -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    GMAIL_PASSWORD: AgAKMd1XB6PgtsSojHgJok0BU27rzvJdW/8T1aTGGMzngmJylYd5eWNr2/J0zSFa+B3uLdvq2VAulDwHSOl0Z6l50iw/mWcpXlh2p4BeRsPEG6wzQdWd3B4eL2BIOt4jMg0aCKPMDpnSlZuRh/Q/hiSS1lllPRHItd3wZGBuV91bEoqOlPgw5fHZetkPo2U4skFw2S4Hl1f3MdZMMBp9KpWZpunuPqsBh4Fpv6WIo1NhYerc8R4N0TGEDFTqTXehbEkxBLlrU5XcmeLhz3SjGexb7Ik3n9U8ryEhoMTW+OpV7CulUO8Ec2CocalSFG1Kuscn3vsnDZyT/HRw3rr1FmeyJtD+VzFKOuWTS2OI/v6mMUe5YiwlT0qGWLcpyYeRzJacmUESacnTiBsppw09J834JHo6ic2+I3lDpmnPqpYn+IcDQakG/2F+0y/FIpKZgjWYI1dJDjDRV5si9Pu1/pcsfhsjTEsVHCiJE4uOCpp3YONBS0I7350a0osX9XQ2sTmZ3sWgqfYkpZA8bVenNmKOok4CB97jAvzgYQbTh+lTZuidswTzOx6XrUW5yUpkI0YoIwpk9u5s8ZhAFa8lHHEBR4Y+cbqHsOxxQ7UD8rI7SrSFOESLdrdVpqI5zMx3ijjqWIcMf1AoseqeJI8+AijMJPdEnsFo7WM1stRRK69fhHpG9lQmeHUxGpESD8n+DFg+2vCff0od4WJTZBcqk5h57+Gp
    GMAIL_USER: AgA2uIrQBu2dB6AD6rceVcLdyKknRrO31ToUkYSayXDXzhTGukGnHRu5KPSY7aILjbngFpcZ8C1pA5If3pG3PJImmRBtuaw9Ge6MrViAyOJOYew+jzIkzoXHEShLMTVlWukFDo7sO9r411zdSLeXdddSYINsnHfOiLyG6xhHVpj5hm2hmF+bUQaqw+q9cm5Lkg4+xIQ8pqYulSf21AlDi/BYpV35MCjTThOKViLnY4Kn0pBTlKwyQtiatbreTRmVprAtENZEH9c0fGfKHaEKE8C2lAroSUueo6SDaqA+yqMvlB+Zvvsc5Z4Xu6AG5CyHm9WxzjxvwR294EmTciZWmIi68p+srwy8Z6oRhIDyX+FhvigQSur8AYcQxZA9/y9ayLOwmveJgZyEFJZ4nX85azKXrgCebP0wnFdbn8Ta/OgsUpfBXDN49qHUe5U9OIcRIZjptoVlidBx3QJO6YgVdyYIfBf4VYuCs7aFwKzDz6276xbOO8Goma3RMQ9C6IFSKnvQR+qXpesBVKcMPok6aVF57avy7383sTW9WdteoseKGJH1bzfR9eZXWqEtZzu3D3cVz+V2ceEczavgLGjwl8ucpkRKjtZDOmggxU+ytwkHS/cc6rBzpcRBG4T4H09SArGoz8JupxuNmY7dieTovQeC1SDewx02yBO6Nap0arl49yed+nhjcsxJEIu80y7hCvv02DJJ6+ChHGt6JOL/RRxoE6azP/zs8w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}