{{ $context := merge (dict "app" $.Values.statusServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    RDB_PASSWORD: AgCQQW0soeYhBr96Hw3jJSUBXLZhm0CclNrWx4g9qqlZlXCO2OLRlIUi8H6pf7km2MHTu9KrnxOYWV+XOpZFHjvGTQ1MV02YG/N6ypMby9BVOToRKSzZsGxAWoKrxbGQzRIzc3s8UVge7YwemgRoQ3aEVcULdiXgdTXE7zhRBYTiFuI2MR0+E5WoLp5RXU3PMfFfktFagxNicFoRmbC6Rd4Wi1P13Uah4P1iqanx1NvPst57irnbJUpfuTMoEoyb76priqhUYGpPbRR9JoyaU1WIuBWUbnplt7RN1AteCEaYAGOJZvI0Qzsak8mjlkLu0EF66hrBH9BPZxtcrN/DFI5D13eze+1jN3umuae6VpAayx2GdkIGJzsFHoO82MCbFXARZBsoXiCFCJ/mkhiUjnAp2wL+vx2XJ0BQ/HCJOuBXv7Ut53gC2Al0wN5y0byLDW7v1LHHM2Ox23wek4mDxz1/BxqToVYsK+9rTB2yASEZ//km9mLTpEvE/5IILRANb5pOLIGU20sOadx/AqQ0i/i4gX2mUEP58jFuCH6CvkW9gXUvmRtGrHh+y9TD5u01Oikg83Vtn7OAVnXvUIe2O9J7kpvWUDXs0gQGdyzcxGAYFZjhVFlx6lzTTU/f4qzoccrF3/oaYTUbuDtKTmOHMQrdPYqUN+3iBOlI9ZMlq59Zr+mrJg4NRGN7Ye5jMFt0u8GfuUqDMIf3IPl+sNoCHiHbPwrrrw==
    RDB_USER: AgA8FqXGSzMJOfOKLkBEW8ij1i0Zh75BUUf9LLlNwiCX1Bbl5gIbcnjiYuo/K+Z4m9Kv7AVvdqMp6XgnSZ0/pdFHz9QInhNn6FAVrWAqXbLtl/i7RU+TSiPt90akbvRTNZpn/0csloK9+XoHuoLzpGvTgE/+nvqAIq91dKrmDI/6LwjsnEBh2JjL6hqwglFrfBLvJBfUsgjkne/3jewSSEOYPzZN4odg1f0Nlwz957H431i/Ke9qZj7nmlpa0aMLhLBqn7TGex2bAzCX2sIT+Re2aY6kN0lnD+HWOuhvPb/zJwcfJqOa7qshYEwlkwpzswbjcpUt/fh+FsNvYjN4yst1U6ATPLWbhdDmvCrQ9rP66hyST1ZqIk7zNe+G4B4nZGWU0QmXyL05TcIDZTKSaxqipO1Q2kXREyl/r1Zj6py9A3H7coHzaJi0hyGLZhYePoC6fdIsPXQhrGWO4kn2KW4AsOJhUTDPPPTOgIo/pFyGZi8YGrV2bADMlu+c155ZB8976OrxBwrILjTSx8gp6RG/Owqb1NFJ/tJlU3BY4DbxI1SN11yTKJX8Uoz0SM48ft0ezyPOEW5GWvsHYWkhVd9X5vJV3QhZUup/ZhYnGXgpGJIe8vPyGv5cyvsJzzWjqtJrjax8XFgB2hVmQW7e8qaUNDTkH2AHUahMn6jLKL/zVVEKzrFbZ7azsIlFgMRS3lMXT7bJBs9M8i6c
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}