{{ $context := merge (dict "app" $.Values.statusServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
spec:
  encryptedData:
    RDB_PASSWORD: AgAIlpmDjPFhAhiM4O/7rzPpQYV6h9FX+1+74hwtca7ToU01bVVZmUuYGJzYSPFVvy1qhG7hRS1xmtMFVURM0PiHZVG1G1cJcqxjPtsBwYd0ySw95/VHhOwp9oe4xCpGw+3dOEDpDEkNbTI5zajLCkjks/ekyu0Hkr9mn0NCgjqd33NQZ74tOpbpKrIpyRlHNgOhebhqiLJwlkCFeDtH2bhVphCYsyy/+xeBpZfCBM/mp5wRY2f6sz7cBAiEQYgCsHZKwlH7yycdKY8hJuoJNBScURQ9//Joig07SatnxMkKQ+u5fg4FDVEWQMH90r2v2oLywEoq6bg0p8LmtQJZkJNmjD0/6UltzlhPaR2fKwoGQtzF+BcWF0T3r+OtCMwnZhaZjgVuXgYDqU1RRvhkZVolr6IYE4pITrCCb+PugnhdWo/dnFgNzerF+VQt6DSdKaCjf0nQZL9DM705IA7yOwQW4/epsgKlmHYWi9GnwRrvaSmALefE3HnVIzLiSQVR943bwPvoULBd3hqNzbklDFdjGI1m/LZw7DYqKPw5kdgvdiuMqLN54XB7FVfHyGQHDpyGvEYn7qNCAn74CIiQI+Wn3E1QNwcbE6twtCizRTiV+dkVAIzXZJ456U9rC09rq9C6vp3upkPOpAPi97h4g87t6u6wOreegJ/bw49JpS2/+2yoM/t1m1I4apn/I8fwJyMI/4LfvxrKomGeIEApdsRuU5Wz2g==
    RDB_USER: AgBKxScXgXaKdQ04af6s277Oo8c03Tzdgc9KvzxoY0SAmyI9zrYM+U9NisDMba1mMLMEbSgT8s5L09Z0CdGA+hHwLzPrM+4BHSv9XrulMyyQZzsWcuHvNor57Vu2D1b88Jt0a9uzCQ2gcZAsSVmrqTIlOc7U47q1ol+lw5B+TdFIiZpWUJzWIGJqkXNLwPMPX4HUApJrfIR2xVjX4o/c7KAIqYevoO2IxhJRnNUTWoBdSB1E2K4s/kEMAHTqyS4fH2UR2n7e/qM1hEW0fePJMez1U/TDjVLSv7+MXiMe+3Oiay0LhBUHxsWndMwdaiq46KYyDNflRWOZqpw7sqeoAmG1tqrEe2jhUMIvjXMwP/aWMP6IHJR/Z63XHvJBe6PEbdK3pLo3Nn22CXLZChOzJ3PaWjzYXTvi5Cm3yK+U45FaxReYLYbxTi3nbf6QXGnWaPF1gb6NYtEG2oW0VEwhTXZof4TRwPdw2N8qTV9to/kE1uOUJVQsvUdkUmV82UotgQCNL0M5VcbZjELAWsCeg5QJoKES22i6THds4ann+fZMe/fA9dY6YBJeS3BWSkayz9UQrXasEcl3GOBkMybkgxqKGJCnCoo6T91Tmxa9AbPoUSojyu6M/pf8CGEeLSWBVmYLCyanZhGZbr4NVZzHeMrMAWFIXuI6bc+4kqAOxK45tStU+H6Q99q4LNIxLpAKj881im85mNSYZKCM
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}