{{ $context := merge (dict "app" $.Values.statusServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    RDB_PASSWORD: AgA3JetBE0YLcmH2D3ryqSZDpsUOTVqExE3WgLArCEeXwuEXg/Squwn6/rVTZBySy+Jqy9yJmSDaXGlFCHrOsrFNwLEHCJQZOQxW9lxJiYJ3yoPP3+2kpurrVpS7bYGclCQ4ej/CNhS47A9A3VTtFT+gpzmXYdB3CMmOJtKlmG8Bhmf/APWt4ldkgVjH84kQL6pulGYGxyIMRM8Lh1f29kjg++MkkZfqQNOwPxKGsVpBx4Ds39W0BrOA9hBt/JIcUvrQ3oke0nDYQzaoQX8RtJ4hpIHe25/3/pO7u+Sk3VlVhMl3kDFbPAtPyymnNAwhJl9kXTkjkt0BPmA84TXUqMMkMoo5r7x+lsvSFzJ/niJgLQ9rHGSFn2kzvu2Yo59ygObJWaWYuZ1LfBzWVQaU1W+wK4FVY3dT+7D+nkFbEs1+Q+XC4bluU9qMI6CG7IniaUp4g9CQaYBQzUgGEwO03XtMRY6m2deZ/tMkuuRTWIaqhBHeIPU612BwPx2Db7+B6mRD1zAsi9rslivJ1xbsnuPPAbgthYQ4+wj/7Wx77QmTAEiG8C413ZaSMcp+0HO/oyV29gjtM3lDKM9fD3cFAKIVf7KD3dfbfPWPlV1UCo18vjmAD/ywwuZ4fqJmPzREuNoqyGKI5OF8BcyaC9h+Nrn8g67X0ZljmZetbqUTbxuM3ZY3+t+/jrA3ucL4zzquO399ncgMT6T6Le+vIGA7fyPsyecSNQ==
    RDB_USER: AgAZ8c0DTLeiAolJUJ/zfABxSybh1E8i/iwm2AJ5MprnCX20pXgcoRuQ5HWIjXL3xG2UybPyerFI8eJt8ZW3dAiRFBnLA4O5GiRx/6aLJcKdOOkxLoOz4ZOfWbN51grqsm3ynjxLb0m1ddQMN1++LwX16cvOY42207YiM/SZHY57mz0MN/udFQDCD/yAh160hrZv5xL05sUwlF9Ze05JZniXlxIjVqQKnT09jA12RozHbl+1bW2gN1nGTQ+Gur/oRu6ylxrsgEp+A+eQOZUOZsToSUQgOiVP/5KXybR60k6CkrVHmtyUZ5oSPJSIn6etlCkaKiu9lixp4hB170BfkLjjVijh87kpRlJ/ozINXNWx3BfmCvmJvCByvRMM/HXjq1tpCWY6uOi9ztiYBaIK87GaZNiXroUviTjZ5F6o6VArU1YcMYZ6c3YQVeUMbgGEwaqcoYulOgN2/uMogBMaUgkmTPpgbh5uCIaaCgK2qmq/0p44saOfsXU+23UIJ1Q72h8yphiZLiIfMg3hHoKRDHG8ECAkN2YzsJ3RdoNku7ZOcswySVCtgtest4xbBBN8MMg4d3TpYH/tZreTjN3ibchaoA26baXdO0LO7Y3NmgumapFYwzeqIzzD13NCT17KEiZ80KflIHySV/0HUaReIH3Z9fvwbqTvE6WnXGgVr86eYaPqxQASY7T/IM7Yd6da2wpAEg+O59cIw0LL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}