{{ $context := merge (dict "app" $.Values.statusServer) . -}}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "neves.name.secret" $context }}
  namespace: {{ $.Values.teamName }}
  labels:
    {{- include "neves.commonLabels" $context | nindent 4 }}
spec:
  encryptedData:
    RDB_PASSWORD: AgAjyOdXb/osEYsj5tFvukgVP1U0GKPxo8zhpdWNsTceSX1NDyoQbA8OV7Htwr8fYT53g2/ISqVqfKjaC8xGxctMlR2b1ejAI01NIfcBte2xQ1gLL2t/hx+0nrE+EkkHM4Qc4tUDAYdb5WlJmPUkxvimPrr7UUJS0YUNNBJuho+GPO9jaT3dVYQUtcc6Z54TNNeixDQwUkMj5blqZEYusTcWRKjjYWo/TVqCi3mz/cEJTkrCYB7RB6OmnSYkSioyz8gGFQV//bJvsCIiHTsE3Bz09UOKoMoBnH3/P+IQiYG82mv0rhCmtoNV8JhBbN89Kejatx/kYYxQuHZwv+J3YHsOhcu8Ss0O90QZHRoeMo2nwf9kIDtd1ZTE/or/NeCEWTMgftyQiqyEe/x4imxF3T0VLksZOt1ZfQswlhkMBht1BoekY6ula+Lu0yQgXlleBXi+HftOoPAygiWjTrwy18XAdcDY/FmJjEBu04n+qgx1dhy8iGwr6RhK4D+7uoU12T+k5sEMogpz3+1ZVis9oGaoiIZtBU4UoAP4KJuvjqP8nF0DAmjaZgVuukkb3O0Abp/sNvsC1TJvPedA3wpo/lDOtcrEKfX23SUhvjdfCJ3K7pi5tKGTlpT1AeKa9Vp2PoExmGFEaZWsM5eA+ntZ2KKBgrMdEVqZRma+i9NbE/ldh4R9tcSzPj4zyr+k+chzQt9uyUJA53y+R+UhD5aH0CowoC0N7Q==
    RDB_USER: AgCKF4iy6x3AzX25vuCUVt/0vayhJ9DaBpdI1aWVDEiWBBmk7LF2+FRLStVlQSd5Tm2zZO9mH5AdDYvW5k7tFOf1Ms5FvBqivm362W70DylYjkJChRKvLWOmUngnKhGFyOAoloSywn87Jq5xtDuCFnNNGypAtBTM8NQa1WASOgRGgG1kbpI6KzKlFzmDugZHZI70rg0cpmztajhEIE8cJMvX+Mc1wn4z/UVz7gD47sDmeKngQ8nYPcuYRJpf+6UaYvMe9H0/6O2smFJDP58YrM/hckDUNSQjYextt7FMoumJHYJ4saIfoOLnjHfgowambDPznngjub8jvoCs6AoYEnPaw7qXZ2Lr8TpnB71fhDx3GmaBInN4H49cn2nAO0S/9C60xi+3TwV1/EhJtm/HQ0Yvq/n0w4Asi+64do+DYg3G8IpjiziEE+u9XJbhiQeVa5Rwt9iNa5idwBiFqC6ry1leOg/AIQW/5O852V1MVOv6LColuNpoYBU/JuzMGGaDSF+gAJiUvrTTB/2EjQtzJS+cmZgXf23X89w97HvhIv574b7hY+eeGFHSTnY6oHORUc4XJrPzm0Q8bm0rAPzeBDfTYBpSarNCQZWhDtXDq3sAmggHKKhgBi4g7+3w/UTAmYrgkyVJ2ywNMHPWgIDM0uILmwUCbx5b+GLegJ3BZPmufCQy4oyXUez+CcUfu15gSFueN8Ls5zkYqVF9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "neves.commonLabels" $context | nindent 8 }}
      name: {{ include "neves.name.secret" $context }}
      namespace: {{ $.Values.teamName }}