apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.monitoring.grafana.name }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    grafana: neves
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    server:
      root_url: {{ printf "https://mnt.%s%s" $.Values.gateway.rootDomain $.Values.monitoring.grafana.path}}
      serve_from_sub_path: "true"